export const quotes = [
  "Setiap angka dalam datamu adalah suara manusia yang dipercayakan padamu. Kamu tidak sedang mengolah data; kamu sedang mengolah cerita dan harapan dari 'N' responden, yang masing-masing adalah nyawa.",
  "Kuantitatif adalah caramu mendengarkan cerita dari ratusan orang sekaligus. Ini adalah bentuk empati dalam skala besar, memastikan tidak ada suara yang terlewat.",
  "Kamu adalah jembatan langka antara hati dan data. Dunia punya banyak orang yang bisa berempati dan banyak orang yang bisa menghitung, tapi sedikit yang mendedikasikan diri untuk melakukan keduanya.",
  "Empati butuh data agar tidak salah sasaran. Penelitianmu ini adalah cara untuk memastikan bahwa bantuan yang akan kamu berikan nanti benar-benar efektif dan berbasis bukti.",
  "Data butuh empati agar tidak kehilangan jiwa. Di tangan seorang konselor sepertimu, angka dan tabel statistik bisa diterjemahkan kembali menjadi solusi kemanusiaan yang hangat.",
  "Uji validitas dan reliabilitas itu memang melelahkan. Anggap saja kamu sedang mengkalibrasi 'alat dengar' (instrumen) agar presisi dan konsisten, karena memberi saran yang tidak valid di dunia nyata akan jauh lebih berbahaya.",
  "Saat SPSS memunculkan 'error', anggap itu sebagai ujian kesabaran. Ingat, kesabaran adalah modal utama seorang konselor saat menghadapi klien yang buntu.",
  "Hipotesis ditolak bukan berarti kamu gagal, itu adalah sebuah penemuan! Kamu baru saja menemukan apa yang TIDAK berhasil, dan itu sama pentingnya dengan menemukan apa yang berhasil.",
  "Dunia butuh konselor yang keputusannya berbasis bukti, bukan sekadar asumsi atau 'perasaan'. Kamu sedang berlatih untuk menjadi salah satu konselor masa depan itu.",
  "Jangan biarkan angka membuatmu lupa pada manusianya. Di balik tabel frekuensi kecemasan, ada siswa-siswa yang benar-benar tidak bisa tidur di malam hari menunggumu menemukan solusinya.",
  "Instrumen penelitianmu adalah alat dengar yang presisi. Kamu meluangkan waktu untuk membuatnya valid dan reliabel agar kamu bisa mendengar masalah dengan akurat, bukan hanya mendengar apa yang ingin kamu dengar.",
  "Kamu unik; seorang humanis yang paham statistik, seorang saintis yang paham perasaan. Banggalah pada jalur langka yang kamu pilih ini.",
  "Skripsimu adalah bentuk kepedulian yang terstruktur dan bertanggung jawab. Kamu tidak mau solusi yang ditawarkan hanya 'kira-kira' berhasil, kamu ingin bukti yang kuat.",
  "Revisi dan coretan dari dosen adalah bentuk kepedulian mereka. Itu adalah proses untuk menguatkan argumenmu, agar karyamu nanti tidak mudah dipatahkan dan benar-benar kokoh.",
  "Kamu sedang belajar menjadi 'ilmuwan data' untuk jiwa manusia. Kamu mengambil 'big data' dari pengalaman manusia yang abstrak dan menerjemahkannya menjadi pola yang bisa ditindaklanjuti.",
  "Olah data, olah rasa. Gunakan logikamu untuk mengolah data, dan gunakan hatimu untuk menginterpretasi maknanya bagi kemanusiaan.",
  "Data yang tidak terdistribusi normal bukanlah akhir dunia. Itu hanya berarti ceritanya lebih unik dari yang kamu duga, dan ia membutuhkan alat analisis (uji alternatif) yang berbeda.",
  "Skala Likert (1-5) bukan sekadar angka. Itu adalah spektrum perasaan, sebuah upaya brilian untuk mengukur sesuatu yang abstrak seperti 'setuju', 'ragu', atau 'bahagia'.",
  "Kamu sedang mengukur perubahan, mengukur harapan, dan mengukur pertumbuhan. Itu adalah pekerjaan yang sangat mulia dan penting.",
  "Saat kamu lelah melihat 'Data View' di SPSS, pejamkan mata sejenak. Bayangkan satu orang yang berhasil kamu bantu berkat temuanmu nanti.",
  "Bimbingan Konseling adalah seni, dan kuantitatif adalah ilmu di baliknya. Kamu sedang memadukan keduanya untuk menciptakan sebuah mahakarya intervensi.",
  "Output SPSS yang terlihat seperti bahasa alien itu adalah bukti. Kamu adalah penerjemahnya, yang akan mengubah kode-kode itu menjadi rekomendasi yang bisa dipahami semua orang.",
  "Lelah itu wajar, tapi menyerah bukan pilihan. Istirahatlah sejenak, datamu akan tetap sabar menunggumu di laptop.",
  "Ingat alasan pertama kamu memilih judul ini. Ingat masalah apa yang membuatmu resah, dan ingat siapa yang ingin kamu bantu. Jadikan itu bahan bakar.",
  "Progres adalah progres, sekecil apapun itu. Satu paragraf selesai, satu tabel berhasil dibuat, satu 'syntax' error teratasi; semua itu adalah kemajuan.",
  "Kamu tidak hanya akan menjadi konselor, kamu akan menjadi 'konselor-peneliti'. Itu adalah level kompetensi yang berbeda, yang sangat dicari dan dihormati.",
  "Tiga karakter kecil ini: p < 0.05, adalah sebuah penemuan. Itu adalah caramu berkata pada dunia secara ilmiah: \"Ini berhasil,\" atau \"Ini berhubungan.\"",
  "Jangan bandingkan progres skripsimu dengan orang lain, terutama yang kualitatif. Setiap penelitian punya jalurnya sendiri, dan jalurmu sedang melatih ketelitian dan objektivitas.",
  "Hasil 'pre-test' adalah potret kejujuran dari sebuah masalah. Hasil 'post-test' adalah potret harapan. Selisih di antara keduanya adalah bukti bahwa intervensi itu bermakna.",
  "Kuantitatif itu melatih ketelitianmu pada detail. Ini adalah skill yang sama persis dengan yang kamu butuhkan untuk mendengarkan detail cerita klien yang sering terlewat.",
  "Konselor berbasis data, bukan berbasis asumsi. Skripsimu adalah latihan terberatmu untuk membiasakan diri bekerja dengan cara itu.",
  "Karyamu akan jadi rujukan dan membantu konselor lain. Penelitianmu akan menambah satu kepingan puzzle dalam ilmu Bimbingan Konseling.",
  "Ini bukan hanya tentang gelar sarjana. Ini tentang membangun fondasi berpikir ilmiah yang akan kamu gunakan seumur hidupmu untuk membantu orang.",
  "Percaya pada prosesnya, percaya pada datamu, dan percaya pada dirimu sendiri. Kamu sudah belajar bertahun-tahun untuk momen ini.",
  "Setiap 'error' adalah kesempatan belajar, dan setiap revisi adalah proses pemurnian. Karyamu akan menjadi lebih tajam dan argumenmu akan semakin kokoh.",
  "Data itu milikmu, kamulah tuannya. Jangan biarkan angka-angka itu mengintimidasimu; kamulah yang akan memberinya makna.",
  "Angka hanyalah angka. Interpretasimu sebagai seorang konselor-lah yang akan memberinya nyawa dan mengubahnya menjadi solusi.",
  "Kamu bukan sekadar ahli statistik, kamu adalah ahli statistik yang punya hati. Kamu adalah konselor yang punya data. Itu adalah kombinasi yang sangat kuat.",
  "Kombinasi ini akan mematikan asumsi yang salah dan menghidupkan solusi yang efektif. Kamu sedang berjuang untuk itu.",
  "Tulis satu kalimat lagi, buat satu tabel lagi, jalankan satu uji lagi. Momentum terbangun dari langkah-langkah kecil yang konsisten.",
  "Kamu sedang membangun sebuah karya ilmiah orisinal. Sesuatu yang kamu ciptakan dari nol dengan keringat dan pikiranmu sendiri. Itu sangat membanggakan.",
  "Jangan lupa makan dan tidur. Otakmu butuh bahan bakar dan istirahat agar bisa menganalisis data dengan jernih.",
  "Validitas adalah tentang kejujuran instrumen. Reliabilitas adalah tentang konsistensi. Skripsi ini sedang mengajarimu tentang pentingnya kejujuran dan konsistensi.",
  "Lihat, skripsi ini mengajarimu banyak hal di luar statistik. Ini tentang karakter, ketekunan, kegigihan, dan kerendahan hati saat direvisi.",
  "Datamu adalah cermin dari realitas di lapangan. Jangan takut melihatnya; apapun hasilnya, itu adalah kebenaran yang akan membebaskanmu dari asumsi.",
  "Kamu hebat. Ingat itu setiap kali kamu merasa ragu. Kamu sudah berani memilih jalan yang menantang ini, itu saja sudah membuktikan keberanianmu.",
  "Selesaikan apa yang sudah kamu mulai. Demi dirimu, demi gelarmu, dan demi semua orang yang akan kamu bantu kelak dengan ilumu ini.",
  "Kekuatanmu adalah objektivitasmu. Kamu sedang dilatih untuk tidak bias, agar bisa melihat klien berdasarkan data, bukan perasaan semata. Itulah profesionalisme.",
  "Tunjukkan pada data itu siapa bosnya. Kaulah penelitinya, kaulah konselornya, dan kaulah yang akan segera lulus.",
  "Membaca output regresi itu seperti membaca peta prediksi. Kamu bisa tahu faktor apa yang paling berpengaruh, sehingga kamu bisa memberi saran yang paling efektif.",
  "Bab 4 adalah tempat di mana data mulai berbicara. Dengarkan baik-baik apa kata mereka, dan biarkan data yang bercerita, bukan asumsimu.",
  "Jangan minder. Kamu punya keahlian langka yang menggabungkan dunia humaniora dan sains. Ini adalah jalur masa depan untuk profesi BK.",
  "Kamu adalah pionir 'Evidence-Based Practice' di levelmu. Kamu sedang membantu profesi BK untuk 'naik kelas', dari sekadar seni menjadi ilmu yang presisi.",
  "Setiap klik di SPSS adalah langkah maju. Setiap tabel yang kamu format adalah kemajuan. Jangan pernah merasa pekerjaanmu sia-sia.",
  "Kamu akan memakai toga itu dan mengingat malam-malam ini. Kamu akan tersenyum bangga karena kamu berhasil melewatinya.",
  "Rasa lelah dan bingungmu itu valid, sama seperti datamu yang harus valid. Akui perasaan itu, istirahat sejenak, lalu kembali berjuang.",
  "Kamu adalah arsitek program intervensi. Datamu adalah denah (blueprint) yang akurat, memastikan bangunan solusimu kokoh dan tidak akan rubuh.",
  "Jangan biarkan orang berkata bahwa BK itu tidak ilmiah. Skripsimu adalah jawaban telak bahwa BK adalah ilmu serius yang peduli pada bukti.",
  "Saat sidang nanti, kamu akan berdiri tegak. Kamu akan mempertahankan setiap angka dan menjelaskan setiap makna, karena kamu benar-benar memahaminya.",
  "Dosen penguji akan melihat kompetensimu dan keseriusanmu. Mereka akan menghargai perjuanganmu menganalisis data, dan mereka akan meluluskanmu.",
  "Rata-rata (mean) dan median adalah caramu melihat di mana kebanyakan orang berada. Ini penting agar kamu tahu siapa yang butuh bantuan ekstra.",
  "Standar deviasi adalah caramu menghargai keunikan. Itu menunjukkan seberapa beragamnya respondenmu, bahwa setiap orang berbeda, bahkan dalam angka.",
  "Semakin kamu paham statistik, semakin kamu paham nuansa kemanusiaan. Itu bukanlah paradoks, itu adalah kebenaran dari profesimu.",
  "Kamu sedang tidak mencari angka yang cantik. Kamu sedang mencari angka yang jujur. Apapun hasilnya, terimalah itu sebagai temuanmu.",
  "Hasil 'tidak signifikan' BUKAN kegagalan. Itu adalah temuan berharga yang memberi tahu kita bahwa 'cara A tidak berpengaruh', sehingga kita bisa fokus ke 'cara B'.",
  "Integritas data lebih penting daripada signifikansi. Kamu sedang dilatih menjadi peneliti dan konselor berintegritas yang tidak memanipulasi data atau membohongi klien.",
  "Skripsi ini adalah kawah candradimuka. Ia sedang menggemblengmu menjadi versi terbaik dari dirimu: seorang konselor yang teliti, logis, sekaligus empatik.",
  "Kamu sudah terlalu jauh untuk berhenti sekarang. Tinggal satu sprint terakhir. Kamu akan sampai di garis finis, dan semua lelahmu akan sepadan.",
  "Menulis abstrak itu sulit karena harus merangkum ratusan halaman. Tapi itu adalah latihan terbaik untuk menyaring inti masalah, skill utama seorang konselor.",
  "Bahkan mengurus format margin dan daftar pustaka itu ada gunanya. Itu melatih ketelitianmu pada detail, agar kamu tidak melewatkan detail kecil dari cerita klien.",
  "Skripsimu adalah sebuah ekosistem utuh, pastikan benang merahnya kuat. Kamu adalah penenun yang memegang kendali atas karya ini.",
  "Kuantitatif itu elegan. Ia menyederhanakan realitas yang kompleks menjadi model yang bisa dipahami, sehingga kamu bisa merancang solusi yang jitu.",
  "'Pembahasan' di Bab 5 adalah tempatmu bersinar. Di sinilah kamu menghubungkan datamu dengan teori, dan memberi makna pada semua angka yang kamu temukan.",
  "Saran yang kamu tulis di skripsimu tidak akan 'asal bunyi'. Saranmu akan lebih didengar dan berdampak karena didukung oleh data yang kuat.",
  "Bayangkan hari sidangmu: kamu memaparkan hasilmu dengan percaya diri. Bayangkan perasaan lega dan bangga saat kamu dinyatakan lulus. Jadikan itu bahan bakar.",
  "Wujudkan bayangan itu menjadi kenyataan. Kamu bisa. Seratus persen kamu bisa.",
  "Percayalah pada kekuatan langkah-langkah kecil yang konsisten. Tiba-tiba, tanpa terasa, kamu akan sampai di halaman terakhir.",
  "Jadilah pribadi yang 'reliabel', konsisten mengerjakan tugasmu hingga tuntas. Dan 'validkan' usahamu dengan hasil yang nyata: lembar pengesahan.",
  "Kamu tidak sendirian dalam perjuangan ini. Ada doa orang tua, dukungan teman, dan semangat dari semua pejuang skripsi lainnya.",
  "Kamu pasti lulus. Teruslah bergerak. Satu kalimat lagi. Satu tabel lagi. Kamu hampir sampai.",
  "Skripsimu adalah bukti cintamu pada profesi ini. Kamu tidak hanya ingin membantu, tapi kamu ingin membantu dengan cara terbaik yang terbukti secara ilmiah.",
  "Saat kamu merapikan daftar pustaka, kamu sedang menghormati para ilmuwan sebelummu. Suatu hari, orang lain akan mengutip namamu dan menghormati karyamu.",
  "Setiap responden yang meluangkan waktu mengisi angketmu sedang berinvestasi padamu. Jangan kecewakan mereka, tuntaskan penelitian ini.",
  "Kelelahanmu adalah bukti bahwa kamu sedang berjuang keras. Itu adalah kelelahan yang produktif, yang akan segera berganti menjadi kelegaan.",
  "Jangan takut pada Bab 4. Itu bukan monster, itu adalah ruang harta karun di mana semua jawaban atas pertanyaan penelitianmu tersimpan.",
  "Berdamailah dengan SPSS. Anggap dia sebagai asisten peneliti yang sangat jujur, teliti, dan sedikit kaku, yang akan membantumu melihat kebenaran.",
  "Kemampuanmu membaca tabel ANOVA akan sama pentingnya dengan kemampuanmu membaca bahasa tubuh klien. Keduanya adalah 'data'.",
  "Kamu sedang mencetak sejarah kecilmu sendiri. Sebuah karya orisinal yang akan tercatat selamanya atas namamu.",
  "Jika kamu buntu, jangan diam. Tanyakan pada dosen, teman, atau bahkan Google. Kebuntuan adalah tanda kamu butuh input baru, bukan tanda kamu bodoh.",
  "Di balik setiap p-value, ada potensi perubahan. Di balik setiap koefisien korelasi, ada pemahaman baru tentang hubungan antar manusia.",
  "Selamat, kamu telah memilih untuk tidak hanya menjadi 'penyembuh', tapi juga 'ilmuwan'. Itu adalah kombinasi yang akan mengubah banyak kehidupan.",
  "Jangan lupakan kesehatan mentalmu sendiri saat meneliti kesehatan mental orang lain. Kamu penting. Istirahatmu penting.",
  "Apa yang kamu lakukan sekarang akan membuat pekerjaanmu sebagai konselor nanti jauh lebih mudah. Kamu akan lebih percaya diri dalam mengambil keputusan.",
  "Suatu hari nanti, kamu akan membuka kembali skripsimu ini. Kamu akan terkagum-kagum, \"Wow, dulu saya bisa ya menyelesaikan analisis serumit ini.\"",
  "Setiap kata yang kamu ketik, setiap data yang kamu input, adalah investasi untuk masa depanmu. Jangan sia-siakan.",
  "Mengapa kuantitatif? Karena kamu peduli pada objektivitas. Kamu ingin membantu semua orang secara adil, terlepas dari bias pribadimu.",
  "Ini adalah maraton, bukan lari cepat. Atur napasmu, atur energimu. Kamu tidak harus selesai hari ini, tapi kamu harus tetap bergerak hari ini.",
  "Penelitianmu adalah mercusuar kecil. Ia akan memberi cahaya dan petunjuk bagi orang lain yang sedang berada di masalah yang sama.",
  "Terima kasih sudah berjuang untuk BK yang lebih ilmiah. Profesi ini membutuhkan orang-orang pemberani sepertimu.",
  "Satu poin terakhir: Lihat angkanya, tapi jangan lupa lihat manusianya. Kamu seorang konselor, dan itu adalah kekuatan terbesarmu."
]
